name: eb-bia-app-beanstalk
services:
  server:
    environment:
      DB_HOST: biadb.c1g4ii6ssn81.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 767397833843.dkr.ecr.us-east-1.amazonaws.com/bia2:1b2b48d
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: eb-bia-app-beanstalk_default
